version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Create Scratch Org
          command: . build/create-scratch-org.sh
  test:
    docker:
     - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Validate Components & Run Tests
          command: . build/setup-uat.sh
      - run: echo "this is the test job"    
  deploy-prod:
    docker:
    - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Login to Production
          command: . build/setup-prod.sh
      - run:
          name: Deploy to Production
          command: . build/deploy-prod.sh
  slack/on-hold:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "deploy my app"
      - slack/notify:
          event: fail
          mentions: '@Karen Rodriguez Labarca'
          #template: basic_fail_1
      - slack/notify:
          event: pass
          #template: success_tagged_deploy_1
workflows:
  version: 2
  validate:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - Master
      - test:
          requires:
            - build
      - slack/on-hold:
          requires:
            - build
            - test
      - hold:
          type: approval
          requires:
            - slack/on-hold
            - build
            - test
      - deploy-prod:
          requires:
           - hold
          filters:
            branches:
              only:
                - RodriBranch
