version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Create Scratch Org
          command: . build/create-scratch-org.sh
     steps:
      - slack/status:
          fail_only: true
          only_for_branches: Master,RodriBranch
          failure_message: ':red_circle: $SFDC_PROD_USER your Job $CIRCLE_JOB failed BUILD' 
          webhook: $SLACK_ACCESS_TOKEN    
  test:
    docker:
     - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Validate Components & Run Tests
          command: . build/setup-uat.sh
      - run: echo "this is the test job"    
    steps:
      - slack/status:
          fail_only: true
          only_for_branches: Master,RodriBranch
          failure_message: ':red_circle: $SFDC_UAT_USER your Job $CIRCLE_JOB failed TEST' 
          webhook: $SLACK_ACCESS_TOKEN
  deploy-prod:
    docker:
    - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Login to Production
          command: . build/setup-prod.sh
      - run:
          name: Deploy to Production
          command: . build/deploy-prod.sh
    steps:
      - slack/status:
          fail_only: false
          #channel: 'CS70KQ92N' use this if you want to deliver to a different channel other than the hook
          only_for_branches: Master
          success_message: ':ok_hand: JOB $CIRCLE_JOB has been successful deploying to production' 
          failure_message: ':red_circle: JOB $CIRCLE_JOB has failed deploying to production!'
          webhook: $SLACK_ACCESS_TOKEN
workflows:
  version: 2
  validate:
    jobs:
      - build:        
          filters:
            branches:
              ignore:
                - Master
      - slack/status:
          requires:
            - builD
      - test:
          requires:
            - build
      - slack/status:
          requires:
            - build
            - test
      - hold:
          type: approval
          requires:
            - build
            - test
      - deploy-prod:
          requires:
           - hold
          filters:
            branches:
              only:
                - RodriBrancH
