version: 2
orbs:
    slack: circleci/slack@4.1.2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Create Scratch Org
          command: . build/create-scratch-org.sh
  test:
    docker:
     - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Validate Components & Run Tests
          command: . build/setup-uat.sh
     # - run:
      #    name: Validate Components & Run Tests
       #   command: . build/test.sh
      - run: echo "this is the test job"    
  request-approval:
    docker:
      - image: circleci/node:latest
    steps:
      - slack/notify:
          channel: https://nectiacloudsolutions.slack.com/archives/C022S0Q8C92
          color: '#42e2f4'
          mentions: '@KAREN RODRIGUEZ LABARCA'
          message: This is a custom message notification
          webhook: https://hooks.slack.com/services/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
deploy-prod:
    docker:
    - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Login to Production
          command: . build/setup-prod.sh
      - run:
          name: Deploy to Production
          command: . build/deploy-prod.sh
workflows:
  version: 2
  validate:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - Master
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
            - test
      - request-approval:
          requires:
            - build
            - test
      - deploy-prod:
          requires:
           - hold
           - request-approval
          filters:
            branches:
              only:
                - RodriBranch
